ARG BUILD_FROM=node:16-alpine3.17
FROM ${BUILD_FROM} 

WORKDIR /app
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    font-noto-emoji \
    font-noto-cjk \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    imagemagick \
    nodejs \
    npm

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser \
    USE_IMAGE_MAGICK=true

COPY package*.json ./
COPY tsconfig*.json ./
COPY local.conf /etc/fonts/local.conf
COPY src ./src

RUN npm ci && npm run build && npm prune --omit=dev


# Copy data for add-on
COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]
