name: ci

on:
  push:
    branches:
      - main

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            sibbl/hass-lovelace-kindle-screensaver:${{ env.PACKAGE_VERSION }},
            sibbl/hass-lovelace-kindle-screensaver:latest
      - name: Build and push HA_Addon AMD64 to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/amd64-base:latest
          platforms: linux/amd64
          push: true
          tags: |
            sibbl/hass-lovelace-kindle-screensaver-ha-addon-amd64:${{ env.PACKAGE_VERSION }},
            sibbl/hass-lovelace-kindle-screensaver-ha-addon-amd64:latest
      - name: Build and push HA_Addon aarch64 to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=homeassistant/aarch64-base:latest
          platforms: linux/arm64
          push: true
          tags: |
            sibbl/hass-lovelace-kindle-screensaver-ha-addon-aarch64:${{ env.PACKAGE_VERSION }},
            sibbl/hass-lovelace-kindle-screensaver-ha-addon-aarch64:latest


      # Currently fails with. I'dont know why, as build womm. Someone? 
      #8 0.148 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/armhf/APKINDEX.tar.gz
      #8 1.271 fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/armhf/APKINDEX.tar.gz
      #8 2.193 ERROR: unable to select packages:
      #8 2.282   chromium (no such package):
      #8 2.282     required by: world[chromium]  
      # - name: Build and push HA_Addon ARMv7 to Docker
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.HA_ADDON
      #     build-args: BUILD_FROM=homeassistant/armhf-base:latest
      #     platforms: linux/armhf
      #     push: true
      #     tags: |
      #       sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7:${{ env.PACKAGE_VERSION }},
      #       sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7:latest

      # - name: Tag git commit
      #   uses: pkgdeps/git-tag-action@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     github_repo: ${{ github.repository }}
      #     version: ${{ env.PACKAGE_VERSION }}
      #     git_commit_sha: ${{ github.sha }}
      #     git_tag_prefix: "v"
